## Libraries for scientific research

In [2]:
import numpy

In [6]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

arthritis = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(arthritis)

In [9]:
print(type(arthritis))

<class 'numpy.ndarray'>


In [11]:
"oxygen"[1:4]

'xyg'

## Operations

In [13]:
double_arthritis = arthritis * 2

In [14]:
print("original")
print(arthritis[:3, 36:])
print("double")
print(double_arthritis[:3, 36:])

original
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
double
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [15]:
triple_arthritis = double_arthritis + arthritis
print(triple_arthritis[:3, 36:])

[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


## Methods(verbs)

In [16]:
print(arthritis.mean())

6.14875


In [17]:
print("maximum inflammation:", arthritis.max())
print("minimum inflammation:", arthritis.min())
print("standard deviation:", arthritis.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [19]:
arthritis.size

2400

In [23]:
patient_0 = arthritis[0, :]
print("maximum inflammation for patient 0:", patient_0.max())

maximum inflammation for patient 0: 18.0


In [22]:
print("maximum inflammation for patient 2:", arthritis[2, :].max())

maximum inflammation for patient 2: 19.0


In [24]:
print(arthritis.max(axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [25]:
print(arthritis.max(axis=0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [26]:
print(arthritis.max(axis=1).shape)
print(arthritis.max(axis=0).shape)

(60,)
(40,)


In [29]:
print(arthritis.std(axis=1).mean())

4.579294680644961
